In [1]:
# Análisis del Covid-19 en Costa Rica

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("data_csv/04_06_CSV.csv")
data.head(10)

,cod_provin,provincia,cod_canton,canton,15/03/2020,16/03/2020,17/03/2020,18/03/2020,19/03/2020,20/03/2020,...,03/04/2020,04/04/2020,05/04/2020,06/04/2020,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,2,Alajuela,201,Alajuela,9,12,13,15,18,22,...,62,65,66,66,NaN,NaN,NaN,NaN,NaN,NaN
1,1,San José,101,San José,3,4,6,10,14,13,...,46,51,53,59,NaN,NaN,NaN,NaN,NaN,NaN
2,1,San José,109,Santa Ana,2,2,3,3,3,6,...,26,26,28,28,NaN,NaN,NaN,NaN,NaN,NaN
3,1,San José,103,Desamparados,4,4,4,4,4,5,...,19,21,21,23,NaN,NaN,NaN,NaN,NaN,NaN
4,1,San José,102,Escazú,4,5,5,6,9,11,...,18,18,19,19,NaN,NaN,NaN,NaN,NaN,NaN
5,2,Alajuela,210,San Carlos,0,0,0,0,0,2,...,10,11,16,17,NaN,NaN,NaN,NaN,NaN,NaN
6,4,Heredia,401,Heredia,1,1,1,1,4,4,...,15,15,16,16,NaN,NaN,NaN,NaN,NaN,NaN
7,1,San José,113,Tibás,1,1,1,1,1,1,...,15,15,16,16,NaN,NaN,NaN,NaN,NaN,NaN
8,1,San José,118,Curridabat,0,0,1,2,3,5,...,14,14,14,14,NaN,NaN,NaN,NaN,NaN,NaN
9,2,Alajuela,203,Grecia,2,2,3,3,3,5,...,14,14,14,14,NaN,NaN,NaN,NaN,NaN,NaN